### ISSUE TITLE
たまに, start_gameが2回呼ばれてしまう

### ISSUE THREAD

**Issue by ishikota** [ishikota/PokerServer#11]
### 問題
最後のメンバがenter_roomしたときのstart_gameが2回よばれてしまう．(呼ばれないときもある)
その場合，gameが進まなくなってしまう．

### 問題詳細
1. start_gameが2回よばれて，2つdealer及び，game_stateが作られる
2. 片方のdealerでaskして,その次にもう片方のdealerでaskすると，ask_counterが更新されてないため，client側で`duplicate message received`ではじかれてしまう．

### 原因
- enter_roomが同じplayerから2回呼ばれてしまい起きる
- room.fiiled_to_capacityの条件を2回くぐり抜けてしまってるのは確認できた
- 最後のplayerがenter_roomのretryした時に起こってるかも
  - server側ではenter_roomを受け付けたことになっているが，client側にそれが伝わっていないのが原因ぽい

**Comment by ishikota** [comment]
client側でduplicateになるだけでなく，以下のサーバ側のエラーで止まることも確認. 

```
Could not execute command from {"identifier"=>"{\"channel\":\"RoomChannel\"}", "command"=>"message", "data"=>"{\"action\" : \"declare_action\" , \"poker_action\" : \"fold\" , \"bet_amount\" : 0 , \"room_id\"    : 1 , \"player_id\"    : 1 , \"credential\" : \"fugafuga\"}"}) [NoMethodError - undefined method `state' for nil:NilClass]: /Users/kota/development/rails/poker_server/poker_server/app/channels/room_channel_delegate.rb:69:in `fetch_dealer' | /Users/kota/development/rails/poker_server/poker_server/app/channels/room_channel_delegate.rb:45:in `declare_action' | /Users/kota/development/rails/poker_server/poker_server/app/channels/room_channel.rb:19:in `declare_action' | /Users/kota/.rvm/gems/ruby-2.3.0@rails_5_0_beta_1/gems/actioncable-5.0.0.beta1/lib/action_cable/channel/base.rb:244:in `public_send' | /Users/kota/.rvm/gems/ruby-2.3.0@rails_5_0_beta_1/gems/actioncable-5.0.0.beta1/lib/action_cable/channel/base.rb:244:in `dispatch_action'
```

サーバ側でgame_stateのrelation_shipをinsertしてる最中にdeclare_actionを受け取って，
room.stateがまだ作られてないため，nilになってるっぽい．

```
   (0.1ms)  begin transaction
  SQL (0.4ms)  INSERT INTO "game_states" ("state") VALUES (?)  [["state", "{\"config\":\"\\u0004\\bo:\\u000bConfig\\b:\\u0013@initial_stackii:\\u000f@max_roundi\\n:\\u0018@small_blind_amounti\\n\",\"table\":\"\\u0004\\bo:\\nTable\\t:\\u0010@dealer_btni\\u0000:\\u000b@seatso:\\nSeats\\u0006:\\r@players[\\u0007o:\\u0010PokerPlayer\\u000b:\\n@nameI\\\"\\tkota\\u0006:\\u0006ET:\\n@uuidI\\\")194db322-7133-4f65-af5e-3aea20de24eb\\u0006;\\fT:\\u000f@hole_card[\\u0007o:\\tCard\\u0007:\\n@suiti\\u0015:\\n@ranki\\u0013o;\\u000f\\u0007;\\u0010i\\u0015;\\u0011i\\u0007:\\u000b@stackid:\\u0016@action_histories[\\u0006{\\nI\\\"\\u000baction\\u0006;\\fTI\\\"\\nRAISE\\u0006;\\fTI\\\"\\u000bamount\\u0006;\\fTi\\nI\\\"\\tpaid\\u0006;\\fTi\\nI\\\"\\u000fadd_amount\\u0006;\\fTi\\nI\\\"\\u000bplayer\\u0006;\\fT{\\tI\\\"\\tname\\u0006;\\fTI\\\"\\tkota\\u0006;\\fTI\\\"\\tuuid\\u0006;\\fTI\\\")194db322-7133-4f65-af5e-3aea20de24eb\\u0006;\\fTI\\\"\\nstack\\u0006;\\fTidI\\\"\\nstate\\u0006;\\fTi\\u0000:\\u000e@pay_infoo:\\u0019PokerPlayer::PayInfo\\u0007:\\f@amounti\\n:\\f@statusi\\u0000o;\\n\\u000b;\\u000bI\\\"\\tmotu\\u0006;\\fT;\\rI\\\")d7626eb2-a230-4420-a9d2-a201975a8f66\\u0006;\\fT;\\u000e[\\u0007o;\\u000f\\u0007;\\u0010i\\r;\\u0011i\\fo;\\u000f\\u0007;\\u0010i\\u0007;\\u0011i\\u0010;\\u0012i_;\\u0013[\\u0006{\\n@\\u0010I\\\"\\nRAISE\\u0006;\\fT@\\u0012i\\u000f@\\u0013i\\u000f@\\u0014i\\n@\\u0015{\\tI\\\"\\tname\\u0006;\\fTI\\\"\\tmotu\\u0006;\\fTI\\\"\\tuuid\\u0006;\\fTI\\\")d7626eb2-a230-4420-a9d2-a201975a8f66\\u0006;\\fTI\\\"\\nstack\\u0006;\\fTi_@\\u001ci\\u0000;\\u0014o;\\u0015\\u0007;\\u0016i\\u000f;\\u0017i\\u0000:\\n@decko:\\tDeck\\u0007:\\u000b@cheatF;\\u0018[5o;\\u000f\\u0007;\\u0010i\\r;\\u0011i\\u000fo;\\u000f\\u0007;\\u0010i\\r;\\u0011i\\u000bo;\\u000f\\u0007;\\u0010i\\u0015;\\u0011i\\to;\\u000f\\u0007;\\u0010i\\u0007;\\u0011i\\no;\\u000f\\u0007;\\u0010i\\u0015;\\u0011i\\u000fo;\\u000f\\u0007;\\u0010i\\u0007;\\u0011i\\bo;\\u000f\\u0007;\\u0010i\\t;\\u0011i\\fo;\\u000f\\u0007;\\u0010i\\t;\\u0011i\\u0007o;\\u000f\\u0007;\\u0010i\\t;\\u0011i\\u000fo;\\u000f\\u0007;\\u0010i\\u0007;\\u0011i\\u0007o;\\u000f\\u0007;\\u0010i\\u0015;\\u0011i\\u0010o;\\u000f\\u0007;\\u0010i\\u0007;\\u0011i\\fo;\\u000f\\u0007;\\u0010i\\u0015;\\u0011i\\u0011o;\\u000f\\u0007;\\u0010i\\t;\\u0011i\\u0012o;\\u000f\\u0007;\\u0010i\\u0007;\\u0011i\\ro;\\u000f\\u0007;\\u0010i\\t;\\u0011i\\u0013o;\\u000f\\u0007;\\u0010i\\t;\\u0011i\\u000eo;\\u000f\\u0007;\\u0010i\\r;\\u0011i\\u0013o;\\u000f\\u0007;\\u0010i\\u0015;\\u0011i\\bo;\\u000f\\u0007;\\u0010i\\u0015;\\u0011i\\u000eo;\\u000f\\u0007;\\u0010i\\r;\\u0011i\\to;\\u000f\\u0007;\\u0010i\\r;\\u0011i\\u0012o;\\u000f\\u0007;\\u0010i\\u0015;\\u0011i\\ro;\\u000f\\u0007;\\u0010i\\u0015;\\u0011i\\no;\\u000f\\u0007;\\u0010i\\t;\\u0011i\\to;\\u000f\\u0007;\\u0010i\\t;\\u0011i\\bo;\\u000f\\u0007;\\u0010i\\r;\\u0011i\\u0011o;\\u000f\\u0007;\\u0010i\\r;\\u0011i\\u000eo;\\u000f\\u0007;\\u0010i\\t;\\u0011i\\u0010o;\\u000f\\u0007;\\u0010i\\r;\\u0011i\\u0007o;\\u000f\\u0007;\\u0010i\\t;\\u0011i\\no;\\u000f\\u0007;\\u0010i\\u0015;\\u0011i\\fo;\\u000f\\u0007;\\u0010i\\u0007;\\u0011i\\u0013o;\\u000f\\u0007;\\u0010i\\u0007;\\u0011i\\u0011o;\\u000f\\u0007;\\u0010i\\r;\\u0011i\\no;\\u000f\\u0007;\\u0010i\\u0015;\\u0011i\\u0012o;\\u000f\\u0007;\\u0010i\\u0007;\\u0011i\\u000fo;\\u000f\\u0007;\\u0010i\\r;\\u0011i\\u0010o;\\u000f\\u0007;\\u0010i\\u0007;\\u0011i\\u000eo;\\u000f\\u0007;\\u0010i\\u0007;\\u0011i\\u000bo;\\u000f\\u0007;\\u0010i\\u0015;\\u0011i\\u000bo;\\u000f\\u0007;\\u0010i\\u0007;\\u0011i\\u0012o;\\u000f\\u0007;\\u0010i\\t;\\u0011i\\u000bo;\\u000f\\u0007;\\u0010i\\u0007;\\u0011i\\to;\\u000f\\u0007;\\u0010i\\t;\\u0011i\\u0011o;\\u000f\\u0007;\\u0010i\\r;\\u0011i\\ro;\\u000f\\u0007;\\u0010i\\r;\\u0011i\\bo;\\u000f\\u0007;\\u0010i\\t;\\u0011i\\r:\\u0014@community_cardo:\\u0012CommunityCard\\u0006:\\u000b@cards[\\u0000\",\"round_count\":1,\"round_manager\":{\"street\":0,\"agree_num\":1,\"next_player\":0},\"broadcaster\":{\"ask_counter\":1}}"]]
RoomChannel#declare_action({"poker_action"=>"fold", "bet_amount"=>0, "room_id"=>1, "player_id"=>1, "credential"=>"fugafuga"})
   (0.8ms)  commit transaction
  Room Load (0.2ms)  SELECT  "rooms".* FROM "rooms" WHERE "rooms"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
   (0.1ms)  begin transaction
  Player Load (0.1ms)  SELECT  "players".* FROM "players" WHERE "players"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  Room Load (0.2ms)  SELECT  "rooms".* FROM "rooms" WHERE "rooms"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  GameState Load (0.1ms)  SELECT  "game_states".* FROM "game_states" INNER JOIN "game_state_relationships" ON "game_states"."id" = "game_state_relationships"."game_state_id" WHERE "game_state_relationships"."room_id" = ? LIMIT ?  [["room_id", 1], ["LIMIT", 1]]
  GameState Load (0.1ms)  SELECT  "game_states".* FROM "game_states" WHERE "game_states"."id" = ? LIMIT ?  [["id", 116], ["LIMIT", 1]]
Could not execute command from {"identifier"=>"{\"channel\":\"RoomChannel\"}", "command"=>"message", "data"=>"{\"action\" : \"declare_action\" , \"poker_action\" : \"fold\" , \"bet_amount\" : 0 , \"room_id\"    : 1 , \"player_id\"    : 1 , \"credential\" : \"fugafuga\"}"}) [NoMethodError - undefined method `state' for nil:NilClass]: /Users/kota/development/rails/poker_server/poker_server/app/channels/room_channel_delegate.rb:69:in `fetch_dealer' | /Users/kota/development/rails/poker_server/poker_server/app/channels/room_channel_delegate.rb:45:in `declare_action' | /Users/kota/development/rails/poker_server/poker_server/app/channels/room_channel.rb:19:in `declare_action' | /Users/kota/.rvm/gems/ruby-2.3.0@rails_5_0_beta_1/gems/actioncable-5.0.0.beta1/lib/action_cable/channel/base.rb:244:in `public_send' | /Users/kota/.rvm/gems/ruby-2.3.0@rails_5_0_beta_1/gems/actioncable-5.0.0.beta1/lib/action_cable/channel/base.rb:244:in `dispatch_action'
  SQL (0.6ms)  INSERT INTO "game_state_relationships" ("room_id", "game_state_id", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["room_id", 1], ["game_state_id", 116], ["created_at", 2016-05-18 11:49:02 UTC], ["updated_at", 2016-05-18 11:49:02 UTC]]
   (0.6ms)  commit transaction
```

**Comment by ishikota** [comment]
```
 24       dealer = @dealer_maker.create(room)
 25       dealer.start_game(players_info(room))                                                                                                                                                                        
 26       game_state = GameState.create(state: dealer.serialize)
 27       GameStateRelationship.create(room_id: room.id, game_state_id: game_state.id)
```
#### [NoMethodError - undefined method `state' for nil:NilClass] の原因
1. 25行目でstart_gameが呼ばれて，clientにaskのmessageが飛ぶ
2. messageを飛ばした後,GameState.createでrecord作成のtransactionが始まる
3. 27行目のrelationshipが作られる前に，clientからの返事がdeclare_actionに届く．
4. fetch_dealerで，`room.game_state.state`でroom.game_stateがnilとなりerror

**Comment by ishikota** [comment]
根本の原因は，dbのtransactionにかかる時間のことを考えずに設計してしまったことで，
その結果，transactionを行う前にclientにmessageを送ってしまって，
transactionが終わってない状態で返事を受け取ってしまった．

**Comment by ishikota** [comment]
### 問題発生の行程(予想)
1. 最後のplayer(Aさん)がenter_roomを送る
2. server側でenter_roomを受け付けて，welcomeメッセージをAさんに送る
  - このwelcomeメッセージをAさんが何らかの理由で受信できず, clientはretryを試みる
3. server側ではgameを開始してしまい,room内のclientにgameのnotificationやaskメッセージを送る
4. Aさんは*3*の時点でPokerPhaseに進めていないので，このメッセージを受け取れない
5. retryが成功すると，新しく2つ目のdealerが作成されてしまい，不具合がおきる
  - Aさんがmessageを受け取っていないので，Aさんの番でとまってしまう．
  - 2つのdealerがそれぞれmessageを送るので，片方のdealerへの返事が，違う方に送られてしまったりする．

### 見落としてた部分
room.filled_to_capaciy(全員そろった)がtrueとなるのは，server側で全員の

### 解決案
全員そろってもゲームを始めず，client側の準備ができたことを確認するmessageを全員から受け取ってからstartするようにする．

**Comment by ishikota** [comment]
### Before
Client2がgameの開始についていけない．
![before_conn](https://cloud.githubusercontent.com/assets/8199616/15446833/1725e20e-1f67-11e6-8f7c-42b62fd48098.png)

### After
Client2の準備が完了できてから，gameを開始する．
![con_after](https://cloud.githubusercontent.com/assets/8199616/15446831/13d8a122-1f67-11e6-857d-f48115bf5a5f.png)

**Comment by ishikota** [comment]
上記方法で実装した結果，(serverとclientの両方でstartの準備ができてからstart_game)
問題が起きなくなったのでclose
